= code to configure host3
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 19-07-2022


After a fresh install of RHEL, these files configure the new host. 

== run

. Install RHEL on host3.
. Log into host3. My user account is fine, the Ansible playbook will ask for the root password.
. Download and run this script
```
curl -o - https://raw.githubusercontent.com/nickhardiman/machine-host3/main/machine-host3-configure.sh | bash -x
```

There's also a script to tweak workstation. 
```
curl -o - https://raw.githubusercontent.com/nickhardiman/machine-host3/main/machine-workstation-configure.sh | bash -x
```


== what is host3

Physical machine host3 is one of the PCs in my home lab.
It hosts a bunch of VMs (virtual machines). 
The build of machine host3 will be described in mind-numbing detail at https://hardiman.consulting/, assuming I ever have free time ever again.

I automate the build of host3 using scripts and playbooks on GitHub.
So building this machine requires two home lab machines and a couple remote service. 
```
my workstation --> host3 <-- GitHub 
                         <-- Red Hat CDN
                         <-- Ansible Galaxy
```

== what are these files

* machine-host3-configure.sh: the shell script to kick off the setup process, run on host3. Downloads RPMs from the CDN, collections from Ansible Galaxy, and my code from GitHub.
* machine-host3-configure.yml: Ansible playbook for host3, run by the script. 
* shell script to run on my workstation: machine-workstation-configure.sh

== todo

Too much! Tired, so very tired. (-_-)

